// Extract OSM POI label points from the same Calgary PMTiles as the basemap.
// No coordinates are authored here. Polygon POIs use Protomaps' label point.
import { open, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { PMTiles } from 'pmtiles';
import { VectorTile } from '@mapbox/vector-tile';
import { PbfReader } from 'pbf';

const input = process.argv[2];
if (!input) throw new Error('Usage: node scripts/calgary-sample.mjs ../.tmp/tiles/calgary.pmtiles');
const file = await open(input);
const archive = new PMTiles({
  getKey: () => input,
  async getBytes(offset, length) {
    const buffer = Buffer.alloc(length);
    const { bytesRead } = await file.read(buffer, 0, length, offset);
    if (bytesRead !== length) throw new Error('Truncated PMTiles');
    return { data: buffer.buffer };
  },
});
const header = await archive.getHeader();
const z = 15;
if (header.maxZoom !== z) throw new Error('Expected a maxzoom 15 Calgary extract');
const bbox = [-114.32, 50.84, -113.86, 51.21];
const tileX = (lon) => Math.floor((lon + 180) / 360 * 2 ** z);
const tileY = (lat) => Math.floor((1 - Math.asinh(Math.tan(lat * Math.PI / 180)) / Math.PI) / 2 * 2 ** z);
const points = new Map();
try {
  for (let x = tileX(bbox[0]); x <= tileX(bbox[2]); x++) {
    for (let y = tileY(bbox[3]); y <= tileY(bbox[1]); y++) {
      const tile = await archive.getZxy(z, x, y);
      if (!tile) continue;
      const pois = new VectorTile(new PbfReader(new Uint8Array(tile.data))).layers.pois;
      for (let i = 0; i < (pois?.length || 0); i++) {
        const f = pois.feature(i).toGeoJSON(x, y, z);
        if (f.geometry.type !== 'Point' || !f.properties.name) continue;
        const [lon, lat] = f.geometry.coordinates;
        if (lon < bbox[0] || lon > bbox[2] || lat < bbox[1] || lat > bbox[3]) continue;
        points.set(f.id, { name: f.properties.name, kind: f.properties.kind, lon, lat, tile_id: f.id });
      }
    }
  }
} finally { await file.close(); }
const all = [...points.values()];
const anchor = all.find((p) => p.name === 'Calgary Tower');
if (!anchor) throw new Error('Calgary Tower missing from source');
const distance = (p) => (p.lat - anchor.lat) ** 2 + ((p.lon - anchor.lon) * Math.cos(anchor.lat * Math.PI / 180)) ** 2;
const selected = [];
for (const [kinds, count] of [[['park'], 10], [['museum'], 6], [['attraction', 'artwork', 'monument', 'memorial', 'viewpoint'], 10], [['cafe'], 4]]) {
  const used = new Set();
  const candidates = all.filter((p) => kinds.includes(p.kind)).sort((a, b) => distance(a) - distance(b) || a.tile_id - b.tile_id)
    .filter((p) => { if (used.has(p.name)) return false; used.add(p.name); return true; }).slice(0, count);
  if (candidates.length !== count) throw new Error(`Need ${count} ${kinds}; found ${candidates.length}`);
  selected.push(...candidates);
}
selected.sort((a, b) => a.name.localeCompare(b.name, 'en'));
const hash = createHash('sha256');
for await (const bytes of createReadStream(input)) hash.update(bytes);
const sourceHash = hash.digest('hex');
const source = `// Calgary places — © OpenStreetMap contributors, ODbL 1.0.\n// https://www.openstreetmap.org/copyright\n// Generated by browser/scripts/calgary-sample.mjs; coordinates are Protomaps POI label points.\n// PMTiles SHA-256: ${sourceHash}\nschema {\n  type Place {\n    name: String\n    kind: String\n    lat: Float\n    lon: Float\n  }\n  display { map { Place }: Default table { Place } graph }\n}\nunique { Place { name } }\n\n` + selected.map((p) =>
  `// Protomaps feature ${p.tile_id}\nmutation { Place(name: ${JSON.stringify(p.name)} && kind: ${JSON.stringify(p.kind)} && lat: ${p.lat} && lon: ${p.lon}) { name kind lat lon } }`
).join('\n') + '\n\nquery { Place { id name kind lat lon } }\n';
await mkdir('samples', { recursive: true });
await writeFile('samples/calgary.zql', source);
console.log(`Generated ${selected.length} places from ${all.length} named POIs; source SHA-256 ${sourceHash}`);
console.log(selected.map((p) => `${p.kind}: ${p.name}`).join('\n'));
