[package]
publish = false
name = "zega-server"
version.workspace = true
edition.workspace = true

[dependencies]
axum = "0.7"
futures-util = { version = "0.3", default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
subtle = "2.6"
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync"] }
zega = { workspace = true }

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }
tempfile = "3"
