[package]
name = "zega-core"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
base64 = { workspace = true }
hmac = { workspace = true }
rsa = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

zega-graph = { workspace = true }
zega-kv = { workspace = true }
zega-parser = { workspace = true }
zega-wal = { workspace = true }

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true }
