[package]
name = "zega-wal"
version.workspace = true
edition.workspace = true

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
zega-graph = { workspace = true }
zega-kv = { workspace = true }
zega-parser = { workspace = true }

[dev-dependencies]
tempfile = "3"
